#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

#rm -rf $OPENSHIFT_DATA_DIR/navajo
#cp -r $OPENSHIFT_REPO_DIR/navajo $OPENSHIFT_DATA_DIR
